### ISSUE TITLE
Exclude paths or feature files

### ISSUE THREAD

**Issue by loic425** [FriendsOfBehat/SuiteSettingsExtension#13]
To customize Behat scenarios on a Sylius project, it should be awesome to exclude some feature files or paths.

**Comment by lchrusciel** [comment]
Hey Loic 👋 😄 

There is an extension for that, but still in a quite early stage https://github.com/FriendsOfBehat/ExcludeSpecificationsExtension

**Comment by loic425** [comment]
@lchrusciel Hi :)
Can we use it for now? or is it too early?

**Comment by lchrusciel** [comment]
I don't remember when I used it last time, but it should work.

**Comment by loic425** [comment]
It works perfectly!
And it's a lot simpler :)

<img width="1951" alt="Capture d’écran 2019-09-25 à 14 56 09" src="https://user-images.githubusercontent.com/8329789/65602769-bc66e000-dfa4-11e9-8a6e-414889971de4.png">
